services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=digit.settings

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 137955137955
      POSTGRES_DB: digit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
